-- MySQL Script generated by MySQL Workbench
-- Sat 18 Dec 2021 01:57:26 AM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gotdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gotdb` ;

-- -----------------------------------------------------
-- Schema gotdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gotdb` ;
USE `gotdb` ;

-- -----------------------------------------------------
-- Table `gotdb`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`locations` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`locations` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `longitude` DOUBLE(8,2) NOT NULL,
  `latitude` DOUBLE(8,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`houses` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`houses` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slogan` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `location_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `houses_location_id_foreign` (`location_id` ASC) VISIBLE,
  CONSTRAINT `houses_location_id_foreign`
    FOREIGN KEY (`location_id`)
    REFERENCES `gotdb`.`locations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`characters` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`characters` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `house_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `date_of_death` DATE NULL DEFAULT NULL,
  `house_leader` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `characters_house_id_foreign` (`house_id` ASC) VISIBLE,
  CONSTRAINT `characters_house_id_foreign`
    FOREIGN KEY (`house_id`)
    REFERENCES `gotdb`.`houses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`assigned_character_titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`assigned_character_titles` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`assigned_character_titles` (
  `character_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` ENUM('HandOfKink', 'Warden', 'Khaleesi', 'KingOfNorth', 'LordCommander') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`character_id`, `title`),
  CONSTRAINT `assigned_character_titles_character_id_foreign`
    FOREIGN KEY (`character_id`)
    REFERENCES `gotdb`.`characters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`notable_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`notable_events` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`notable_events` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('War', 'Weeding') NOT NULL,
  `date` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`character_notable_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`character_notable_event` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`character_notable_event` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `character_id` BIGINT(20) UNSIGNED NOT NULL,
  `notable_event_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `character_notable_event_character_id_foreign` (`character_id` ASC) VISIBLE,
  INDEX `character_notable_event_notable_event_id_foreign` (`notable_event_id` ASC) VISIBLE,
  CONSTRAINT `character_notable_event_character_id_foreign`
    FOREIGN KEY (`character_id`)
    REFERENCES `gotdb`.`characters` (`id`),
  CONSTRAINT `character_notable_event_notable_event_id_foreign`
    FOREIGN KEY (`notable_event_id`)
    REFERENCES `gotdb`.`notable_events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`character_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`character_friends` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`character_friends` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `left_id` BIGINT(20) UNSIGNED NOT NULL,
  `right_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `character_friends_left_id_foreign` (`left_id` ASC) VISIBLE,
  INDEX `character_friends_right_id_foreign` (`right_id` ASC) VISIBLE,
  CONSTRAINT `character_friends_left_id_foreign`
    FOREIGN KEY (`left_id`)
    REFERENCES `gotdb`.`characters` (`id`),
  CONSTRAINT `character_friends_right_id_foreign`
    FOREIGN KEY (`right_id`)
    REFERENCES `gotdb`.`characters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`non_humans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`non_humans` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`non_humans` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `species` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`character_non_human`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`character_non_human` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`character_non_human` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `character_id` BIGINT(20) UNSIGNED NOT NULL,
  `non_human_id` BIGINT(20) UNSIGNED NOT NULL,
  `from_year` YEAR(4) NULL DEFAULT NULL,
  `to_year` YEAR(4) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `character_non_human_character_id_foreign` (`character_id` ASC) VISIBLE,
  INDEX `character_non_human_non_human_id_foreign` (`non_human_id` ASC) VISIBLE,
  CONSTRAINT `character_non_human_character_id_foreign`
    FOREIGN KEY (`character_id`)
    REFERENCES `gotdb`.`characters` (`id`),
  CONSTRAINT `character_non_human_non_human_id_foreign`
    FOREIGN KEY (`non_human_id`)
    REFERENCES `gotdb`.`non_humans` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`character_relatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`character_relatives` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`character_relatives` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `left_id` BIGINT(20) UNSIGNED NOT NULL,
  `right_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `character_relatives_left_id_foreign` (`left_id` ASC) VISIBLE,
  INDEX `character_relatives_right_id_foreign` (`right_id` ASC) VISIBLE,
  CONSTRAINT `character_relatives_left_id_foreign`
    FOREIGN KEY (`left_id`)
    REFERENCES `gotdb`.`characters` (`id`),
  CONSTRAINT `character_relatives_right_id_foreign`
    FOREIGN KEY (`right_id`)
    REFERENCES `gotdb`.`characters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`religions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`religions` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`religions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`character_religion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`character_religion` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`character_religion` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `character_id` BIGINT(20) UNSIGNED NOT NULL,
  `religion_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `character_religion_character_id_foreign` (`character_id` ASC) VISIBLE,
  INDEX `character_religion_religion_id_foreign` (`religion_id` ASC) VISIBLE,
  CONSTRAINT `character_religion_character_id_foreign`
    FOREIGN KEY (`character_id`)
    REFERENCES `gotdb`.`characters` (`id`),
  CONSTRAINT `character_religion_religion_id_foreign`
    FOREIGN KEY (`religion_id`)
    REFERENCES `gotdb`.`religions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotdb`.`location_notable_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotdb`.`location_notable_event` ;

CREATE TABLE IF NOT EXISTS `gotdb`.`location_notable_event` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `location_id` BIGINT(20) UNSIGNED NOT NULL,
  `notable_event_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `location_notable_event_location_id_foreign` (`location_id` ASC) VISIBLE,
  INDEX `location_notable_event_notable_event_id_foreign` (`notable_event_id` ASC) VISIBLE,
  CONSTRAINT `location_notable_event_location_id_foreign`
    FOREIGN KEY (`location_id`)
    REFERENCES `gotdb`.`locations` (`id`),
  CONSTRAINT `location_notable_event_notable_event_id_foreign`
    FOREIGN KEY (`notable_event_id`)
    REFERENCES `gotdb`.`notable_events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
